name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v1
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: configure
      run: mkdir build
    - name: cmake
      run: cmake -B build/ && cd build/ && make
    - name: execute
      run: cd build/ && ./program1 
  
