name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v1
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: configure
      run: mkdir build
    - name: cmake
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .
    - name: run
      working-directory: ${{runner.workspace}}/build
      run: ./program1
  
